services:
  app:
    container_name: pobre-project-django
    build:
      context: ./
      dockerfile: .devops/Docker/Dockerfile
    env_file:
      - ./.env
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./:/app
    command:
      ["sh", "-c", "pip install debugpy && python -m debugpy --listen 0.0.0.0:5678 --wait-for-client project/manage.py migrate && python -m debugpy --listen 0.0.0.0:5678 --wait-for-client project/manage.py runserver 0.0.0.0:8000"]
    networks:
      - pobre-project

networks:
  pobre-project:
    name: pobre-project
    driver: bridge