# Generated by Django 5.1.1 on 2024-10-29 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('goal', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('emergency_fund', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('financial_goal', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('direct', 'Direct'), ('indirect', 'Indirect')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='budgets.budget')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(max_length=50)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budgets.budget')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(max_length=50)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_sources', to='budgets.budget')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('actual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='budgets.budget')),
            ],
        ),
    ]
