# Generated by Django 5.1.2 on 2024-11-05 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('goal', models.TextField(verbose_name='Objetivo')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Término')),
                ('emergency_fund', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fundo de Emergência')),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Renda Total')),
                ('total_expense', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Despesa Total')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('type', models.CharField(choices=[('fixed', 'Fixo'), ('variable', 'Variável')], max_length=10, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('frequency', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('semiannual', 'Semestral'), ('annual', 'Anual')], max_length=10, verbose_name='Frequência')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budgets.budget', verbose_name='Orçamento')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('frequency', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal'), ('semiannual', 'Semestral'), ('annual', 'Anual')], max_length=10, verbose_name='Frequência')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_sources', to='budgets.budget', verbose_name='Orçamento')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('actual_income', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Renda Real')),
                ('actual_expense', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Despesa Real')),
                ('notes', models.TextField(verbose_name='Notas')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='budgets.budget', verbose_name='Orçamento')),
            ],
        ),
    ]
