# Generated by Django 5.1.2 on 2024-10-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
        migrations.AlterModelOptions(
            name='persontype',
            options={},
        ),
        migrations.AddField(
            model_name='person',
            name='document_number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Document Number'),
        ),
    ]
